apiVersion: v1
kind: Pod
metadata:
  name: ansible-pod
spec:
  containers:
    - name: ansible-container
      image: ansible-pod:latest
      imagePullPolicy: Never         # <-- use minikube load
      command: ["/bin/bash", "-c", "sleep infinity"]
      tty: true